### ISSUE TITLE
[Question] Eclipse - CDT parser vs Antlr  

### ISSUE THREAD

**Issue by nort3x** [toasterofbread/KJna#2]
Hi @toasterofbread,
thanks for imitating this nice project <3
we are looking for projects similar to this for generating some bindings for scientific C libraries in KMP

i noticed you are parsing C header files using Antlr, which is robust!
but i saw similar projects who use [Eclipse CDT AST Parser](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.cdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fcdt%2Fcore%2Fdom%2Fast%2FIASTTranslationUnit.html)  like [this project](https://github.com/danfickle/cpp-to-java-source-converter/blob/master/src/main/java/com/github/danfickle/cpptojavasourceconverter/Main.java)

what are your thoughts? would this be feasible with current structure of the project?
CDT is an actively maintained project and makes parsing battle tested

**Comment by sayaka-sh** [comment]
Eclipse CDT was one of the options I considered when picking a parser library, but I didn't use it because:

- It's a Java library and this is a KMP library. While using a Java library within this project's parsing module would be possible, it would restrict its use to Kotlin/JVM projects only.
- It looks like it can only be included directly using a Jar, which (I assumed) would make packaging inconvenient.

I haven't looked into how Eclipse CDT works, but I'd imagine it could work as a replacement for Antlr in this project's current state. The code responsible for parsing headers is fairly minimal.

What makes you prefer Eclipse CDT, by the way? Antlr also appears to be well-maintained, as does the Kotlin binding I'm using, and I had zero issues using it for this project.

**Comment by nort3x** [comment]
i just noticed lots of effort on CToken values (PackageInfo and CHeaderParser),
if i remember correctly CDT will comes in with the whole package of preprocessing, traversing and provide a fair set of tokens as well, so it reduces the code that should be maintained tomorrow - thats the only  advantage i'm thinking about, it's the backbone of an IDE and probably deal with these concerns better than Another Tool for Language Recognition  

about it being just a jar and distribution, yes that would be a disadvantage
 
 about that being java library and you require multiplatform for this i assume you use parser in generation step (which runs on the jvm already) so i don't think that would be a problem
 
 forgive me if i made some wrong assumption, the project is still young and there is no documents and i checked few classes, i'm still figuring out what exactly we are doing here :D

**Comment by sayaka-sh** [comment]
> i just noticed lots of effort on CToken values (PackageInfo and CHeaderParser),
> if i remember correctly CDT will comes in with the whole package of preprocessing, traversing and provide a fair set of tokens as well, so it reduces the code that > should be maintained tomorrow - thats the only advantage i'm thinking about, it's the backbone of an IDE and probably deal with these concerns better than Another > Tool for Language Recognition

Interesting, I never actually tried using CDT but maybe I should've.

> about that being java library and you require multiplatform for this i assume you use parser in generation step (which runs on the jvm already) so i don't think that would be a problem

Yeah, that was just my reasoning for selecting Antlr originally. It's not really a concern now that I'm using JCPP which is pure Java, but JCPP was a late addition and before this I think it still would've worked as a KMP library.

> forgive me if i made some wrong assumption, the project is still young and there is no documents and i checked few classes, i'm still figuring out what exactly we are doing here :D

The project is definitely very young. Unfortunately I'm unlikely to improve it significantly or add any documentation as it's really just a means to an end for one of my other projects. I thought I might as well make it into a standalone library in case I need it for another project down the line. Contributions such as implementing CDT would be more than welcome, but at the end of the day it's not really meant for general use in the first place so I'd understand if you wanted to stay away.

**Comment by nort3x** [comment]
i would love to contribute and I'm first trying to understand what is happening here,

one advantage point this project has is simply it's gradle plugin for jextract, it auto downloads jextract, finds headers based on include path (which other's simply don't) and it's configurable to the bone, and supports multiple header files!

at first step i think we should decouple this from everything else (like generation of kotlin binding) and deliver it as is

we are planning to use this project extensively so we would definitely contribute to it

let's be in touch
